"use client";

import Link from "next/link";
import Image from "next/image";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Upload,
  Brain,
  Search,
  ShieldCheck,
  Clock,
  MessageSquare,
  Zap,
  FileText,
  Globe,
  Server,
  Lock,
  BarChart3,
  GitCompare,
  AlertTriangle,
  Eye,
} from "lucide-react";

const fadeUp = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
};

const FEATURES = [
  {
    icon: Brain,
    title: "AI-Powered Root Cause Analysis",
    description:
      "Claude AI analyzes your entire bundle holistically — correlating pod failures, node conditions, events, and config drift to identify the actual root cause, not just symptoms.",
    color: "#818cf8",
  },
  {
    icon: Search,
    title: "Deep Triage Engine",
    description:
      "Before AI even runs, a deterministic triage engine scans for 20+ issue categories: crash loops, OOMKills, image pull failures, RBAC errors, DNS problems, TLS expirations, scheduling failures, and more.",
    color: "#f87171",
  },
  {
    icon: Clock,
    title: "Temporal Archaeology",
    description:
      "Reconstructs a timeline of what happened by mining timestamps from events, conditions, pod transitions, and deployment changes. See the sequence of failures unfold chronologically.",
    color: "#fbbf24",
  },
  {
    icon: GitCompare,
    title: "Change Correlation",
    description:
      "Automatically detects what changed right before failures started — config updates, image version bumps, resource limit changes — and correlates them with the onset of issues.",
    color: "#e879f9",
  },
  {
    icon: MessageSquare,
    title: "Interactive Investigation",
    description:
      "Ask follow-up questions in natural language. The AI has full context of your bundle and can drill into specific pods, explain error chains, or suggest remediation steps.",
    color: "#22d3ee",
  },
  {
    icon: Eye,
    title: "Uncertainty Reporting",
    description:
      "Unlike tools that only show what they found, TroubleShootAI also reports what it couldn't determine — missing data, ambiguous signals, and areas that need manual investigation.",
    color: "#6ee7b7",
  },
  {
    icon: ShieldCheck,
    title: "Evidence-Based Findings",
    description:
      "Every finding cites specific files, log lines, and resource specs from your bundle. No hallucinated diagnoses — everything is grounded in actual evidence you can verify.",
    color: "#10b981",
  },
  {
    icon: Zap,
    title: "Anomaly Detection",
    description:
      "Compares failing pods against healthy ones in the same deployment to spot differences in node placement, resource limits, image versions, env config, and restart patterns.",
    color: "#f59e0b",
  },
];

const STEPS = [
  {
    step: "1",
    icon: Upload,
    title: "Upload Your Bundle",
    description:
      "Drag and drop a Kubernetes support bundle (.tar.gz) generated by tools like Replicated Troubleshoot, kubectl, or custom collectors.",
  },
  {
    step: "2",
    icon: FileText,
    title: "Automated Triage",
    description:
      "The triage engine parses cluster resources, pod specs, events, logs, node conditions, and configs. It flags issues using deterministic pattern matching — no tokens spent on what regex can catch.",
  },
  {
    step: "3",
    icon: Brain,
    title: "AI Analysis",
    description:
      "Claude AI receives the triage output (never raw files) and performs root cause analysis, generates hypotheses, builds a timeline, and produces actionable fix recommendations.",
  },
  {
    step: "4",
    icon: BarChart3,
    title: "Explore Results",
    description:
      "Navigate findings through a dashboard with severity-sorted issues, a validation view with 20+ triage categories, a visual timeline, and an interactive Q&A interface.",
  },
];

const TECH_DETAILS = [
  {
    icon: Server,
    title: "Architecture",
    items: [
      "Next.js frontend with real-time WebSocket updates",
      "FastAPI backend with async streaming extraction",
      "Support bundles can be 500MB+ — all processing is streamed, never loaded fully into memory",
      "Triage runs first (deterministic), AI runs second (intelligent) — tokens are only spent on findings that need reasoning",
    ],
  },
  {
    icon: Lock,
    title: "Security & Privacy",
    items: [
      "Multi-layer data scrubbing before any data reaches the AI",
      "Environment variable values are redacted; only names are preserved for diagnostics",
      "Internal IPs, hostnames, and cluster names are scrubbed",
      "Entropy-based detection catches secrets that don't match known patterns",
      "Log content is treated as untrusted input with prompt injection guards",
      "All redactions are audit-logged for compliance",
    ],
  },
  {
    icon: Globe,
    title: "What It Scans",
    items: [
      "Pod specs, statuses, conditions, and restart histories",
      "Container logs (current and previous) with OOM, crash, and error detection",
      "Node conditions, capacities, and allocatable resources",
      "Deployments, StatefulSets, DaemonSets, and ReplicaSets",
      "ConfigMaps, Secrets (references only), and environment variables",
      "Events (Warning type), RBAC errors, NetworkPolicies",
      "DNS (CoreDNS), TLS certificates, Ingress configs",
      "Resource quotas, LimitRanges, and scheduling constraints",
    ],
  },
];

export default function AboutPage() {
  return (
    <div className="relative z-10 min-h-screen p-6 md:p-12">
      <div className="mx-auto max-w-4xl">
        {/* Back link */}
        <motion.div {...fadeUp} transition={{ duration: 0.4 }}>
          <Link
            href="/login"
            className="inline-flex items-center gap-2 text-sm transition-colors hover:underline underline-offset-2 mb-8"
            style={{ color: "var(--accent-light)" }}
          >
            <ArrowLeft size={14} />
            Back to sign in
          </Link>
        </motion.div>

        {/* Hero */}
        <motion.div
          {...fadeUp}
          transition={{ duration: 0.6, delay: 0.05 }}
          className="flex flex-col items-center text-center mb-16"
        >
          <motion.div
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.1, duration: 0.5 }}
            className="mb-6"
          >
            <Image
              src="/logo.svg"
              alt="TroubleShootAI logo"
              width={72}
              height={72}
              priority
              className="h-[72px] w-[72px] object-contain"
            />
          </motion.div>
          <h1
            className="text-3xl md:text-4xl font-bold tracking-tight mb-4"
            style={{ color: "var(--foreground-bright)" }}
          >
            TroubleShootAI
          </h1>
          <p
            className="text-base md:text-lg max-w-2xl leading-relaxed"
            style={{ color: "var(--muted)" }}
          >
            AI-powered Kubernetes support bundle forensics. Upload a support bundle
            and get instant root cause analysis, correlated timelines, and actionable
            fix recommendations — all grounded in evidence from your actual cluster data.
          </p>
        </motion.div>

        {/* How It Works */}
        <motion.section {...fadeUp} transition={{ duration: 0.5, delay: 0.1 }} className="mb-16">
          <h2
            className="text-xl font-semibold mb-6"
            style={{ color: "var(--foreground-bright)" }}
          >
            How It Works
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {STEPS.map((step) => (
              <div key={step.step} className="glass-card p-5 flex gap-4">
                <div
                  className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl"
                  style={{ background: "rgba(99, 102, 241, 0.15)" }}
                >
                  <step.icon size={18} style={{ color: "var(--accent-light)" }} />
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span
                      className="text-[10px] font-bold uppercase tracking-widest"
                      style={{ color: "var(--accent-light)" }}
                    >
                      Step {step.step}
                    </span>
                  </div>
                  <h3
                    className="text-sm font-semibold mb-1"
                    style={{ color: "var(--foreground-bright)" }}
                  >
                    {step.title}
                  </h3>
                  <p className="text-xs leading-relaxed" style={{ color: "var(--muted)" }}>
                    {step.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </motion.section>

        {/* Key Features */}
        <motion.section {...fadeUp} transition={{ duration: 0.5, delay: 0.15 }} className="mb-16">
          <h2
            className="text-xl font-semibold mb-6"
            style={{ color: "var(--foreground-bright)" }}
          >
            Key Features
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {FEATURES.map((feature) => (
              <div key={feature.title} className="glass-card p-5 flex gap-4">
                <div
                  className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl"
                  style={{ background: `${feature.color}18` }}
                >
                  <feature.icon size={18} style={{ color: feature.color }} />
                </div>
                <div>
                  <h3
                    className="text-sm font-semibold mb-1"
                    style={{ color: "var(--foreground-bright)" }}
                  >
                    {feature.title}
                  </h3>
                  <p className="text-xs leading-relaxed" style={{ color: "var(--muted)" }}>
                    {feature.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </motion.section>

        {/* Technical Details */}
        <motion.section {...fadeUp} transition={{ duration: 0.5, delay: 0.2 }} className="mb-16">
          <h2
            className="text-xl font-semibold mb-6"
            style={{ color: "var(--foreground-bright)" }}
          >
            Under the Hood
          </h2>
          <div className="flex flex-col gap-4">
            {TECH_DETAILS.map((section) => (
              <div key={section.title} className="glass-card p-5">
                <div className="flex items-center gap-3 mb-3">
                  <section.icon size={18} style={{ color: "var(--accent-light)" }} />
                  <h3
                    className="text-sm font-semibold"
                    style={{ color: "var(--foreground-bright)" }}
                  >
                    {section.title}
                  </h3>
                </div>
                <ul className="flex flex-col gap-2">
                  {section.items.map((item) => (
                    <li
                      key={item}
                      className="flex gap-2 text-xs leading-relaxed"
                      style={{ color: "var(--muted)" }}
                    >
                      <span
                        className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full"
                        style={{ background: "var(--accent-light)" }}
                      />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </motion.section>

        {/* Issue Categories */}
        <motion.section {...fadeUp} transition={{ duration: 0.5, delay: 0.25 }} className="mb-16">
          <h2
            className="text-xl font-semibold mb-6"
            style={{ color: "var(--foreground-bright)" }}
          >
            Issue Categories Detected
          </h2>
          <div className="glass-card p-5">
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              {[
                { label: "Pod Failures", icon: AlertTriangle, color: "#f87171" },
                { label: "Crash Loops", icon: AlertTriangle, color: "#f87171" },
                { label: "OOMKilled", icon: AlertTriangle, color: "#ef4444" },
                { label: "Image Pull Errors", icon: AlertTriangle, color: "#f59e0b" },
                { label: "Node Conditions", icon: Server, color: "#fbbf24" },
                { label: "Deployment Issues", icon: Server, color: "#fbbf24" },
                { label: "Config Drift", icon: GitCompare, color: "#e879f9" },
                { label: "RBAC Errors", icon: Lock, color: "#e879f9" },
                { label: "Resource Quotas", icon: BarChart3, color: "#f59e0b" },
                { label: "Network Policies", icon: Globe, color: "#22d3ee" },
                { label: "DNS Issues", icon: Globe, color: "#22d3ee" },
                { label: "TLS / Certificates", icon: ShieldCheck, color: "#22d3ee" },
                { label: "Scheduling Failures", icon: Clock, color: "#fbbf24" },
                { label: "Event Escalations", icon: Zap, color: "#f59e0b" },
                { label: "Silence Signals", icon: Eye, color: "#6ee7b7" },
              ].map((cat) => (
                <div key={cat.label} className="flex items-center gap-2 py-1.5">
                  <cat.icon size={12} style={{ color: cat.color }} />
                  <span className="text-xs" style={{ color: "var(--foreground)" }}>
                    {cat.label}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </motion.section>

        {/* CTA */}
        <motion.div
          {...fadeUp}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="text-center pb-12"
        >
          <Link href="/login" className="btn-primary inline-flex items-center gap-2 text-sm">
            Get Started
            <ArrowLeft size={14} className="rotate-180" />
          </Link>
        </motion.div>
      </div>
    </div>
  );
}
