export const STAGES = [
  "Extracting bundle",
  "Indexing resources",
  "Scanning pods",
  "Scanning nodes",
  "Scanning deployments",
  "Scanning configs",
  "Detecting drift",
  "Analyzing silence signals",
  "AI pod analysis",
  "AI node analysis",
  "Temporal archaeology",
  "Generating predictions",
];

export const STAGE_SHORT = [
  "Extract",
  "Index",
  "Pods",
  "Nodes",
  "Deploy",
  "Config",
  "Drift",
  "Silence",
  "AI Pods",
  "AI Nodes",
  "Temporal",
  "Predict",
];

export const STAGE_KEY_TO_INDEX: Record<string, number> = {
  extracting: 0,
  indexing: 1,
  triaging: 2,
  scanning_pods: 2,
  scanning_nodes: 3,
  scanning_deployments: 4,
  scanning_configs: 5,
  detecting_drift: 6,
  analyzing_silence: 7,
  analyzing: 8,
  ai_pod_analysis: 8,
  archaeology: 8,
  analysts: 8,
  ai_node_analysis: 9,
  temporal_archaeology: 10,
  prediction: 11,
  generating_predictions: 11,
  silence: 7,
  synthesis: 11,
  uncertainty: 11,
};
